<?php

define('SENDSTUDIO_DATABASE_TYPE', 'mysql');
define('SENDSTUDIO_DATABASE_USER', 'root');
define('SENDSTUDIO_DATABASE_PASS', '');
define('SENDSTUDIO_DATABASE_HOST', 'localhost');
define('SENDSTUDIO_DATABASE_NAME', 'emmdb');
define('SENDSTUDIO_DATABASE_UTF8PATCH', '1');
define('SENDSTUDIO_TABLEPREFIX', 'email_');
define('SENDSTUDIO_LICENSEKEY', 'IEM-NDIxYWE5MGUwNzlmYTMyNmI2NDk0ZjgxMmFkMTNlNzktMWUyMzg1MjgyMGI5MTU0MzE2YzdjMDZlMmI3YmEwNTEtLXY8ODQzNzRhOTM1YTc1ZDk3Yz4tMC0wLTAtOQojOjA6MDowOjA6OTk5OjA6YmY5NDVlYjY=');
define('SENDSTUDIO_APPLICATION_URL', 'http://localhost/interspire/iem');
define('SENDSTUDIO_IS_SETUP', 1);
define('SENDSTUDIO_DEFAULTCHARSET', 'UTF-8');
